export const DEFAULT_URL = "http://localhost:8080";
export const CONFIRMATION_URL = "/confirmation";
export const REGISTRATION_URL = "/registration";
export const REGISTRATION_DATA_URL = "/registration-data";
export const STUDENTS_URL = "/students";
export const TEACHERS_URL = "/teachers";
export const PASSWORD_URL_PARAM = "?password=";
export const EMAIL_URL_PARAM = "?email=";
export const SLASH = "/";