export const DEFAULT_URL = "http://localhost:8080";
export const CONFIRMATION_URL = "/confirmation";
export const REGISTRATION_URL = "/registration";
export const REGISTRATION_DATA_URL = "/registration-data";
export const AUTHENTICATION_URL = "/authentication"
export const STUDENTS_URL = "/students";
export const TEACHERS_URL = "/teachers";
export const ADMINS_URL = "/admins";
export const GROUPS_URL = "/groups";
export const GROUP_URL = "/group";
export const SUBJECTS_URL = "/subjects";
export const EMAIL_URL = "/email";
export const PASSWORD_CHANGE_URL = "/password-change";
export const PASSWORD_REPAIR_URL = "/password-repair";
export const PASSWORD_URL_PARAM = "?password=";
export const EMAIL_URL_PARAM = "?email=";
export const SLASH = "/";

export const STUDENT_ROLE = "ROLE_STUDENT";
export const TEACHER_ROLE = "ROLE_TEACHER";
export const ADMIN_ROLE = "ROLE_ADMIN";
